baseurl = "/"
languageCode = "sv-se"
title = "Alviks Måleri"

[menu]
  [[menu.main]]
    identifier = "vasteras"
    name = "Västerås"
    title = "Västerås section"
    url = "/kontakt/vasteras/"
    parent = "kontakt"
  [[menu.main]]
    identifier = "stockholm"
    name = "Stockholm"
    title = "Stockholm section"
    url = "/kontakt/stockholm/"
    parent = "kontakt"
  [[menu.main]]
    identifier = "uppsala"
    name = "Uppsala"
    title = "Uppsala section"
    url = "/kontakt/uppsala/"
    parent = "kontakt"
  [[menu.main]]
    identifier = "nyheter"
    name = "Nyheter"
    title = "Nyheter sectiion"
    url = "/nyheter/"
    weight = 4
  [[menu.main]]
    identifier = "karriar"
    name = "Jobba hos oss"
    title = "Karriär sectiion"
    url = "/karriar/"
    weight = 3
  [[menu.main]]
    identifier = "kontakt"
    name = "Kontakt"
    title = "Kontakt sectiion"
    url = "/kontakt/"
    weight = 6
    hasChildren = true
  [[menu.main]]
    identifier = "tjanster"
    name = "Tjänster"
    title = "Tjänster sectiion"
    url = "/tjanster/"
    weight = 1
  [[menu.main]]
    identifier = "referenser"
    name = "Referenser"
    title = "Referenser sectiion"
    url = "/referenser/"
    weight = 2
  [[menu.main]]
    identifier = "om-oss"
    name = "Om oss"
    title = "Om oss sectiion"
    url = "/om-oss/"
    weight = 5
