baseurl = "/"
languageCode = "sv-se"
title = "Alviks Måleri"
summaryLength = 30
pluralizeListTitles = false

[permalinks]
  referenser = "/referenser/:title/"
  referenserkategorier = "/referenser/kategorier/:title/"
  vad-vi-gor = "/vad-vi-gor/:title/"
  vad-vi-gor_kategorier = "/kategorier/:title/"

[menu]
  [[menu.main]]
    identifier = "whatwedo"
    name = "Vad vi gör"
    title = "Vad vi gör sectiion"
    url = "/vad-vi-gor/"
    weight = 1
  [[menu.main]]
    identifier = "referenser"
    name = "Referenser"
    title = "Referenser sectiion"
    url = "/referenser/"
    weight = 2
  [[menu.secondary]]
    identifier = "om-oss"
    name = "Om oss"
    title = "Om oss sectiion"
    url = "/om-oss/"
    weight = 5
  [[menu.secondary]]
    identifier = "vasteras"
    name = "Västerås"
    title = "Västerås section"
    url = "/kontakt/västerås/"
    parent = "kontakt"
  [[menu.secondary]]
    identifier = "stockholm"
    name = "Stockholm"
    title = "Stockholm section"
    url = "/kontakt/stockholm/"
    parent = "kontakt"
  [[menu.secondary]]
    identifier = "uppsala"
    name = "Uppsala"
    title = "Uppsala section"
    url = "/kontakt/uppsala/"
    parent = "kontakt"
  [[menu.secondary]]
    identifier = "kontakt"
    name = "Kontakt"
    title = "Kontakt sectiion"
    url = "/kontakt/"
    weight = 3
    hasChildren = true
  [[menu.secondary]]
    identifier = "trendmagasin"
    name = "TRENDmagasin"
    title = "TRENDmagasin sectiion"
    url = "/trendmagasin/"
    weight = 7
