backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "global"
    label: "Global"
    files:
      - file: "site/data/global.yml"
        label: "General"
        name: "general"
        format: "yaml"
        fields:
          - {label: "Logotype", name: "logo", widget: "image"}
          - {label: "Copyright", name: "copy", widget: "text"}
      - file: "site/data/nav.yml"
        label: "Navbar"
        name: "navbar"
        format: "yaml"
        fields:
          - {label: "Bakgrundsbild", name: "bgimage", widget: "image"}
      - file: "site/data/footer.yml"
        label: "Footer"
        name: "footer"
        format: "yaml"
        fields:
          - {label: "Ingress", name: "ingress", widget: "text"}
          - {label: "Address block", name: "ablock", widget: "list", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Facebooklänk", name: "fblink", widget: "string"},
              {label: "Instagramlänk", name: "iglink", widget: "string"},
              {label: "Address info", name: "info", widget: "list", fields: [
                {label: "Text", name: "text", widget: "string"},
                {label: "Länk", name: "link", widget: "string", required: false}
                ]}
              ]}
          - {label: "Social media heading", name: "socialheading", widget: "string"}
          - {label: "Social media icon", name: "socialicon", widget: "list", fields: [
              {label: "Icon", name: "icon", widget: "image"},
              {label: "Link", name: "link", widget: "string"},
            ]}
        editor:
          preview: false
  - name: "service"
    label: "Tjänster (Service)"
    folder: "site/content/service"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tjanster"
    label: "Tjänster"
    folder: "site/content/tjanster"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "karriar"
    label: "Karriär"
    folder: "site/content/karriar"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Sista ansökningsdag", name: "lastday", widget: "date"}
      - {label: "Kontor", name: "office", widget: "select", options: ["Stockholm", "Uppsala", "Västerås"]}
      - {label: "Länk ansökan", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "reference"
    label: "Referens"
    folder: "site/content/reference"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "referenser"
    label: "Referenser"
    folder: "site/content/referenser"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "nyheter"
    label: "Nyheter"
    folder: "site/content/nyheter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "kontor"
    label: "Kontor"
    folder: "site/content/kontakt"
    create: true
    fields:
      - {label: Titel, name: title, widget: string}
      - {label: Ingress, name: ingress, widget: text}
      - {label: Telefon, name: phone, widget: string}
      - {label: E-postadress, name: email, widget: string}
      - {label: Koordinater (Lat/Long), name: coordinates, widget: string}
      - {label: "Besöksadress information", name: "visitinfo", widget: "list", fields: [
          {label: "Text", name: "text", widget: "string"},
          {label: "Länk", name: "link", widget: "string", required: false}
        ]}
      - {label: "Postadress information", name: "postinfo", widget: "list", required: false, fields: [
          {label: "Text", name: "text", widget: "string"},
          {label: "Länk", name: "link", widget: "string", required: false}
        ]}
      - {label: Medarbetare, name: coworker, widget: list, fields: [
          {label: Namn, name: name, widget: string},
          {label: E-postadress, name: email, widget: string},
          {label: Bild, name: image, widget: image, required: false},
          {label: Position, name: position, widget: string},
          {label: Telefonnummer, name: phone, widget: string},
        ]}
  - name: "pages"
    label: "Sidor"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Supertitle, name: supertitle, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Illustration, name: illustration, widget: image}
          - {label: Partners, name: partners, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: Kontakt, name: contact, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Text, name: text, widget: text},
              {label: Länk, name: link, widget: string},
              {label: Knapp text, name: btntext, widget: string}
            ]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Kontakta oss"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/kontakt/_index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/om-oss/_index.md"
        label: "Om oss"
        name: "om-oss"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/about/_index.md"
        label: "Om oss (old)"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
