backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "global"
    label: "Global"
    editor:
      preview: false
    files:
      - file: "site/data/global.yml"
        label: "General"
        name: "general"
        format: "yaml"
        fields:
          - {label: "Logotype", name: "logo", widget: "image"}
          - {label: "Copyright", name: "copy", widget: "text"}
          - {label: "Kontakt titel", name: "contacttitle", widget: "string"}
          - {label: "Kontakt ingress", name: "contactingress", widget: "text"}
          - {label: "Kontor", name: "office", widget: "list", fields: [
              {label: "Kontor", name: "name", widget: "string"},
              {label: "Telefon", name: "phone", widget: "string"},
              {label: "E-postadress", name: "email", widget: "string"}
            ]}
      - file: "site/data/nav.yml"
        label: "Navbar"
        name: "navbar"
        format: "yaml"
        fields:
          - {label: "Bakgrundsbild", name: "bgimage", widget: "image"}
      - file: "site/data/footer.yml"
        label: "Footer"
        name: "footer"
        format: "yaml"
        fields:
          - {label: "Ingress", name: "ingress", widget: "text"}
          - {label: "Address block", name: "ablock", widget: "list", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Facebooklänk", name: "fblink", widget: "string"},
              {label: "Instagramlänk", name: "iglink", widget: "string"},
              {label: "Address info", name: "info", widget: "list", fields: [
                {label: "Text", name: "text", widget: "string"},
                {label: "Länk", name: "link", widget: "string", required: false}
                ]}
              ]}
          - {label: "Social media heading", name: "socialheading", widget: "string"}
          - {label: "Social media icon", name: "socialicon", widget: "list", fields: [
              {label: "Icon", name: "icon", widget: "image"},
              {label: "Link", name: "link", widget: "string"},
            ]}
        editor:
          preview: false
  - name: "whatwedo"
    editor:
      preview: false
    label: "Vad vi gör"
    folder: "site/content/vad-vi-gor"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Page weight", name: "weight", widget: "number"}
  - name: "karriar"
    editor:
      preview: false
    label: "Karriär"
    folder: "site/content/karriar"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Sista ansökningsdag", name: "lastday", widget: "date", required: false}
      - {label: "Kontor", name: "office", widget: "select", options: ["Stockholm", "Uppsala", "Västerås"]}
      - {label: "Länk ansökan", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "referenser"
    label: "Referenser"
    editor:
      preview: false
    folder: "site/content/referenser"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "nyheter"
    label: "Nyheter"
    editor:
      preview: false
    folder: "site/content/nyheter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "trendmagasin"
    label: "TRENDmagasin"
    editor:
      preview: false
    folder: "site/content/trendmagasin"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "PDF-fil", name: "pdf_file", widget: "file"}
  - name: "kontor"
    label: "Kontor"
    editor:
      preview: false
    folder: "site/content/kontakt"
    create: true
    fields:
      - {label: Titel, name: title, widget: string}
      - {label: Ingress, name: ingress, widget: text}
      - {label: Telefon, name: phone, widget: string}
      - {label: E-postadress, name: email, widget: string}
      - {label: Koordinater (Lat/Long), name: coordinates, widget: string}
      - {label: "Besöksadress information", name: "visitinfo", widget: "list", fields: [
          {label: "Text", name: "text", widget: "string"},
          {label: "Länk", name: "link", widget: "string", required: false}
        ]}
      - {label: "Postadress information", name: "postinfo", widget: "list", required: false, fields: [
          {label: "Text", name: "text", widget: "string"},
          {label: "Länk", name: "link", widget: "string", required: false}
        ]}
      - {label: Medarbetare, name: coworker, widget: list, fields: [
          {label: Namn, name: name, widget: string},
          {label: E-postadress, name: email, widget: string},
          {label: Bild, name: image, widget: image, required: false},
          {label: Position, name: position, widget: string},
          {label: Telefonnummer, name: phone, widget: string},
        ]}
  - name: "pages"
    label: "Sidor"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Supertitle, name: supertitle, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Title 2, name: title_2, widget: string, required: false}
          - {label: Title 3, name: title_3, widget: string, required: false}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image}
          - {label: Illustration, name: illustration, widget: image}
          - {label: Partners, name: partners, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: Kontakt, name: contact, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Text, name: text, widget: text},
              {label: Länk, name: link, widget: string},
              {label: Knapp text, name: btntext, widget: string}
            ]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/kontakt/_index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/om-oss/_index.md"
        label: "Om oss"
        name: "om-oss"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
