backend:
  name: git-gateway
  branch: staging

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "global"
    label: "Global"
    editor:
      preview: false
    files:
      - file: "site/data/global.yml"
        label: "Allmänt"
        name: "general"
        format: "yaml"
        fields:
          - {label: "Logotype", name: "logo", widget: "image"}
          - {label: "Copyright", name: "copy", widget: "text"}
          - {label: "Kontakt titel", name: "contacttitle", widget: "string"}
          - {label: "Kontakt ingress", name: "contactingress", widget: "text"}
          - {label: "Kontor", name: "office", widget: "list", fields: [
              {label: "Kontor", name: "name", widget: "string"},
              {label: "Telefon", name: "phone", widget: "string"},
              {label: "E-postadress", name: "email", widget: "string"}
            ]}
      - file: "site/data/nav.yml"
        label: "Navbar"
        name: "navbar"
        format: "yaml"
        fields:
          - {label: "Bakgrundsbild", name: "bgimage", widget: "image"}
      - file: "site/data/footer.yml"
        label: "Sidfot"
        name: "footer"
        format: "yaml"
        fields:
          - {label: "Ingress", name: "ingress", widget: "text"}
          - {label: "Address block", name: "ablock", widget: "list", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Facebooklänk", name: "fblink", widget: "string"},
              {label: "Instagramlänk", name: "iglink", widget: "string"},
              {label: "Address info", name: "info", widget: "list", fields: [
                {label: "Text", name: "text", widget: "string"},
                {label: "Länk", name: "link", widget: "string", required: false}
                ]}
              ]}
          - {label: "Social media heading", name: "socialheading", widget: "string"}
          - {label: "Social media icon", name: "socialicon", widget: "list", fields: [
              {label: "Ikon", name: "icon", widget: "image"},
              {label: "Länk", name: "link", widget: "string"},
            ]}
        editor:
          preview: false
  - name: "projects"
    editor:
      preview: false
    label: "Projekt"
    folder: "site/content/projects"
    create: true
    fields:
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Ordning", name: "weight", widget: "number"}
  - name: "whatwedo"
    editor:
      preview: false
    label: "Vad vi gör"
    folder: "site/content/vad-vi-gor"
    create: true
    fields:
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Ordning", name: "weight", widget: "number"}
      - {label: Underkategorier, name: "subcategories" , widget: list, fields: [
          {label: "Rubrik", name: "title", widget: "string"},
          {label: "Bild", name: "image", widget: "image"},
          {label: "Innehåll", name: "body", widget: "markdown"},
          {label: "Ordning", name: "weight", widget: "number"}
        ]}
  - name: "referenser"
    label: "Referenser"
    editor:
      preview: false
    folder: "site/content/referenser"
    create: true
    fields:
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Kategori", name: "referenserkategorier", widget: "relation", collection: "referenserkategorier", searchFields: [ "title", "body" ], valueField: "title"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Ordning", name: "weight", widget: "number"}
  - name: "referenserkategorier"
    editor:
      preview: false
    label: "Referenser - Kategorier"
    folder: "site/content/referenserkategorier"
    create: true
    fields:
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Ordning", name: "weight", widget: "number"}
  - name: "trendmagasin"
    label: "TRENDmagasin"
    editor:
      preview: false
    folder: "site/content/trendmagasin"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "PDF-fil", name: "pdf_file", widget: "file"}
  - name: "kontor"
    label: "Kontor"
    editor:
      preview: false
    folder: "site/content/kontakt"
    create: true
    fields:
      - {label: Titel, name: title, widget: string}
      - {label: Ingress, name: ingress, widget: text}
      - {label: Telefon, name: phone, widget: string}
      - {label: E-postadress, name: email, widget: string}
      - {label: Koordinater (Lat/Long), name: coordinates, widget: string}
      - {label: "Besöksadress information", name: "visitinfo", widget: "list", fields: [
          {label: "Text", name: "text", widget: "string"},
          {label: "Länk", name: "link", widget: "string", required: false}
        ]}
      - {label: "Postadress information", name: "postinfo", widget: "list", required: false, fields: [
          {label: "Text", name: "text", widget: "string"},
          {label: "Länk", name: "link", widget: "string", required: false}
        ]}
      - {label: Lediga jobb, name: vacant_jobs, widget: list, fields: [
          {label: Titel, name: title, widget: string},
          {label: "Innehåll", name: "body", widget: "markdown"}
        ]}
      - {label: Medarbetare, name: coworker, widget: list, fields: [
          {label: Namn, name: name, widget: string},
          {label: E-postadress, name: email, widget: string},
          {label: Bild, name: image, widget: image, required: false},
          {label: Position, name: position, widget: string},
          {label: Telefonnummer, name: phone, widget: string},
        ]}
  - name: "pages"
    label: "Sidor"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Startsida"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Title 2, name: title_2, widget: string, required: false}
          - {label: Title 3, name: title_3, widget: string, required: false}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Rubrik Projektslider, name: slider_heading, widget: string, required: false}
          - {label: Text Projektslider, name: slider_text, widget: text, required: false}
          - {label: Partners, name: partners, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"}
            ]}
      - file: "site/content/kontakt/_index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/om-oss/_index.md"
        label: "Om oss"
        name: "om-oss"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
